<a href="https://colab.research.google.com/github/PRAJWAL2108/DEEP-LEARNING/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=np.arange(16)    #1D Tensor
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x.ndim

1

In [3]:
x=np.array(25)    #0D Tensor
x.ndim

0

In [4]:
y=np.array([15,20,10,32,45])
y

array([15, 20, 10, 32, 45])

In [5]:
y.ndim

1

In [6]:
!pip install mxnet
from mxnet import np, npx
npx.set_np()

In [7]:
z=np.arange(25,100,50)
z

array([25., 75.])

In [8]:
z.shape #shape-gives format of tensor

(2,)

In [9]:
z.size #size-number of elements in the array

2

In [10]:
a=np.arange(1,13)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [11]:
a=a.reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [12]:
b=a.reshape(4,3)
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [13]:
c=np.arange(15)
c=c.reshape(3,5)
c

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [14]:
np.random.normal(0,1,size=(3,6))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 ,  0.4838046 ,  1.0434403 ,
         0.29956347],
       [ 1.1839255 ,  0.15302546,  1.8917114 , -1.1688148 , -1.2347414 ,
         1.5580711 ],
       [-1.771029  , -0.5459446 , -0.45138445, -2.3556297 ,  0.57938355,
         0.5414402 ]])

In [15]:
#(mean, standard deviation, size of matrix)  np=numpy object which is object of numpy package
np.random.normal(1,4,size=(4,4))   

array([[-6.424328  , 11.714026  , -6.9075184 ,  6.0185375 ],
       [ 0.16792315, -1.1950958 ,  1.9776871 , -1.7242575 ],
       [ 0.85135734,  0.45873666, -0.95099974,  2.508925  ],
       [ 0.90953094,  2.640658  ,  3.2984567 ,  3.2850728 ]])

In [16]:
x=np.array([[2, 11, 4, 3], [1, 5, 3, 4], [4, 10, 2, 6]])
x

array([[ 2., 11.,  4.,  3.],
       [ 1.,  5.,  3.,  4.],
       [ 4., 10.,  2.,  6.]])

In [17]:
x=x.reshape(6,2)
x

array([[ 2., 11.],
       [ 4.,  3.],
       [ 1.,  5.],
       [ 3.,  4.],
       [ 4., 10.],
       [ 2.,  6.]])

In [18]:
import numpy as mp
x=mp.array([1,2,3,4])
y=mp.array([3,4,5,6])
x,y

(array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [19]:
x
y

array([3, 4, 5, 6])

In [20]:
x,y

(array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [21]:
x+y

array([ 4,  6,  8, 10])

In [22]:
x-y

array([-2, -2, -2, -2])

In [23]:
x*y

array([ 3,  8, 15, 24])

In [24]:
x/y

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [25]:
x**y

array([   1,   16,  243, 4096])

In [26]:
x = mp.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
y=np.array([[2, 11, 4, 3], [1, 5, 3, 4], [4, 10, 2, 6]])
y

array([[ 2., 11.,  4.,  3.],
       [ 1.,  5.,  3.,  4.],
       [ 4., 10.,  2.,  6.]])

In [28]:
#z=np.concatenate([x,y],axis=0)
#z

In [29]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,2,2])
a*b

array([2, 4, 6])

In [30]:
x=10
y=5
x,y

(10, 5)

In [31]:
before = id(y)
y = y + x
after=id(y)
before,after

(94638241581696, 94638241582016)

In [32]:
z = np.zeros_like(y)
print('ID of z is:',id(z))

ID of z is: 140193724042336


In [33]:
import numpy as np
a=np.array([1,2,3])
a.shape

(3,)

In [34]:
b=np.array([2,2,2])
b.shape

(3,)

In [35]:
a*b

array([2, 4, 6])

In [36]:
a=np.array([1,2,3])
b=2
a*b

array([2, 4, 6])

In [37]:
z=np.array([1,2,3,4,5])
z[0], z[-1], z[-2]  

(1, 5, 4)

In [38]:
z[1:3]

array([2, 3])

In [39]:
z[0:4]

array([1, 2, 3, 4])

In [40]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([3,3,3,3,3])
beforeComp=id(y)
beforeComp

140193724005952

In [41]:
y[:]=x+y
afterComp=id(y)
afterComp

140193724005952