<a href="https://colab.research.google.com/github/PRAJWAL2108/DEEP-LEARNING/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Implement the example on linear algebra using Tensorflow and Numpy

In [ ]:
import numpy as np
x=np.arange(16)    #1D Tensor
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
x.ndim

1

In [ ]:
x=np.array(25)    #0D Tensor
x.ndim

0

In [ ]:
y=np.array([15,20,10,32,45])
y

array([15, 20, 10, 32, 45])

In [ ]:
y.ndim

1

In [ ]:
!pip install mxnet
from mxnet import np, npx
npx.set_np()

     |████████████████████████████████| 38.7MB 89kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [ ]:
z=np.arange(25,100,50)
z

array([25., 75.])

In [ ]:
z.shape #shape-gives format of tensor

(2,)

In [ ]:
z.size #size-number of elements in the array

2

In [ ]:
a=np.arange(1,13)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
a=a.reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
b=a.reshape(4,3)
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
c=np.arange(15)
c=c.reshape(3,5)
c

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [ ]:
np.random.normal(0,1,size=(3,6))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 ,  0.4838046 ,  1.0434403 ,
         0.29956347],
       [ 1.1839255 ,  0.15302546,  1.8917114 , -1.1688148 , -1.2347414 ,
         1.5580711 ],
       [-1.771029  , -0.5459446 , -0.45138445, -2.3556297 ,  0.57938355,
         0.5414402 ]])

In [ ]:
#(mean, standard deviation, size of matrix)  np=numpy object which is object of numpy package
np.random.normal(1,4,size=(4,4))   

array([[-6.424328  , 11.714026  , -6.9075184 ,  6.0185375 ],
       [ 0.16792315, -1.1950958 ,  1.9776871 , -1.7242575 ],
       [ 0.85135734,  0.45873666, -0.95099974,  2.508925  ],
       [ 0.90953094,  2.640658  ,  3.2984567 ,  3.2850728 ]])

In [ ]:
x=np.array([[2, 11, 4, 3], [1, 5, 3, 4], [4, 10, 2, 6]])
x

array([[ 2., 11.,  4.,  3.],
       [ 1.,  5.,  3.,  4.],
       [ 4., 10.,  2.,  6.]])

In [ ]:
x=x.reshape(6,2)
x

array([[ 2., 11.],
       [ 4.,  3.],
       [ 1.,  5.],
       [ 3.,  4.],
       [ 4., 10.],
       [ 2.,  6.]])

In [ ]:
import numpy as mp
x=mp.array([1,2,3,4])
y=mp.array([3,4,5,6])
x,y

(array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [ ]:
x
y

array([3, 4, 5, 6])

In [ ]:
x,y

(array([1, 2, 3, 4]), array([3, 4, 5, 6]))

In [ ]:
x+y

array([ 4,  6,  8, 10])

In [ ]:
x-y

array([-2, -2, -2, -2])

In [ ]:
x*y

array([ 3,  8, 15, 24])

In [ ]:
x/y

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [ ]:
x**y

array([   1,   16,  243, 4096])

In [ ]:
x = mp.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y=np.array([[2, 11, 4, 3], [1, 5, 3, 4], [4, 10, 2, 6]])
y

array([[ 2., 11.,  4.,  3.],
       [ 1.,  5.,  3.,  4.],
       [ 4., 10.,  2.,  6.]])

In [ ]:
#z=np.concatenate([x,y],axis=0)
#z

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,2,2])
a*b

array([2, 4, 6])

In [ ]:
x=10
y=5
x,y

(10, 5)

In [ ]:
before = id(y)
y = y + x
after=id(y)
before,after

(94100942584448, 94100942584768)

In [ ]:
z = np.zeros_like(y)
print('ID of z is:',id(z))

ID of z is: 139928914528096


In [ ]:
import numpy as np
a=np.array([1,2,3])
a.shape

(3,)

In [ ]:
b=np.array([2,2,2])
b.shape

(3,)

In [ ]:
a*b

array([2, 4, 6])

In [ ]:
a=np.array([1,2,3])
b=2
a*b

array([2, 4, 6])

In [ ]:
z=np.array([1,2,3,4,5])
z[0], z[-1], z[-2]  

(1, 5, 4)

In [ ]:
z[1:3]

array([2, 3])

In [ ]:
z[0:4]

array([1, 2, 3, 4])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([3,3,3,3,3])
beforeComp=id(y)
beforeComp

139928872251264

In [ ]:
y[:]=x+y
afterComp=id(y)
afterComp

139928872251264